-- CREATION OF TABLE
CREATE TABLE EMPLOYEE (--TABLE 1/DATA OF STUDENTS(EMPLOYEE)
  student_id INTEGER PRIMARY KEY,
  name VARCHAR(50),
  dept VARCHAR(20),
  year INT
);
CREATE TABLE MARK(--TABLE 2/MARK OF STUDENTS
    student_id INTEGER PRIMARY KEY,
    DB INTEGER,
    java INTEGER,
    Python INTEGER,
    os INTEGER
);

--INSERT
INSERT INTO EMPLOYEE--INSERT ON TABLE 1/Without args
VALUES
(101,'RAM','CSE',3),
(102,'ARUN','MECH',2),
(103,'AMAL','EEE',3),
(104,'VICKY','ECE',2),
(105,'VIGNESH','CSE',2);--END OF TABLE

INSERT INTO MARK(student_id,DB)--INSERT ON TABLE 2/With args
VALUES
  (201,99),
  (202,75),
  (203,100),
  (204,57),
  (205,98);

--CONDITION STMTS
SELECT * FROM EMPLOYEE
 WHERE student_id < 106;

--UPDATE

UPDATE EMPLOYEE --UPDATE_1
set year = 3
WHERE student_id = 102;
SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE --UPDATE_2
set year = 3
WHERE student_id = 104;
SELECT * FROM EMPLOYEE;

--DELETE
DELETE FROM EMPLOYEE
WHERE student_id = 105;

--OPERATION
SELECT * FROM EMPLOYEE
 WHERE year =  3 OR year = 2;

--IN KEYS
SELECT * FROM EMPLOYEE
WHERE dept IN ('CSE','EEE');

--LIKE
SELECT * FROM EMPLOYEE
 WHERE name LIKE 'V%';

 --GROUP BY
SELECT year ,COUNT(*) FROM EMPLOYEE
 GROUP BY year;

--ORDER BY ASCENDING ORD
SELECT * FROM EMPLOYEE
ORDER BY student_id ASC;

--ORDER BY DECENDING
SELECT * FROM EMPLOYEE
ORDER BY student_id DESC;

SELECT * FROM MARK;

